name: Build ZMK firmware

on:
  push:
    branches: [ "master" ]
    paths:
      - "config/**"
      - "west.yml"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-dev-arm:stable

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: West init (use repo root manifest)
        run: west init -l .

      - name: West update
        run: west update

      - name: Build settings_reset
        run: west build -s app -d build/settings_reset -b nice_nano_v2 -- -DSHIELD="settings_reset"
