name: Build ZMK firmware

on:
  push:
    branches: [ "master" ]
    paths:
      - "config/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: nice_nano_v2
            shield: corne_left nice_view_adapter nice_view
          - board: nice_nano_v2
            shield: corne_right nice_view_adapter nice_view
          - board: nice_nano_v2
            shield: settings_reset

    steps:
      - name: Checkout config repo
        uses: actions/checkout@v4

      - name: Checkout ZMK (upstream)
        uses: actions/checkout@v4
        with:
          repository: zmkfirmware/zmk
          ref: main
          path: zmk

      - name: Build
        run: |
          west init -l zmk/app
          west update
          west zephyr-export
          west build -s zmk/app -d build/${{ matrix.shield }} -b ${{ matrix.board }} -- \
            -DZMK_CONFIG=${{ github.workspace }}/config \
            -DSHIELD="${{ matrix.shield }}"

      - name: Upload UF2
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.shield }}
          path: build/${{ matrix.shield }}/zephyr/*.uf2
