name: Build ZMK firmware

on:
  push:
    branches: [ "master" ]
    paths:
      - "config/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: nice_nano_v2
            shield: corne_left nice_view_adapter nice_view
          - board: nice_nano_v2
            shield: corne_right nice_view_adapter nice_view
          - board: nice_nano_v2
            shield: settings_reset

    steps:
      - name: Checkout config repo
        uses: actions/checkout@v4

      - name: Build ZMK
        uses: zmkfirmware/zmk-build-action@v1
        with:
          # Din config ligger i repoets /config mappe
          config: ${{ github.workspace }}/config
          board: ${{ matrix.board }}
          shield: ${{ matrix.shield }}

      - name: Upload UF2
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.shield }}
          path: |
            **/*.uf2
