name: Build ZMK firmware

on:
  push:
    branches: [ "master" ]
    paths:
      - "config/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: left
            board: nice_nano_v2
            shield: "corne_left nice_view_adapter nice_view"
          - name: right
            board: nice_nano_v2
            shield: "corne_right nice_view_adapter nice_view"
          - name: settings_reset
            board: nice_nano_v2
            shield: "settings_reset"

    steps:
      - name: Checkout config repo
        uses: actions/checkout@v4

      - name: Build ZMK
        uses: zmkfirmware/zmk-build-action@v1
        with:
          config: config
          board: ${{ matrix.board }}
          shield: ${{ matrix.shield }}

      - name: Upload UF2
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: "**/*.uf2"
