name: Build ZMK firmware

on:
  push:
    branches: [ "master" ]
    paths:
      - "config/**"
      - "west.yml"
      - "build.yaml"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-dev-arm:stable

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: West init
        run: west init -l config

      - name: West update
        run: west update

      - name: Debug tree
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -type d -name app -print
          find . -maxdepth 4 -name west.yml -print

      - name: Build settings_reset
        run: west build -s zmk/app -d build/settings_reset -b nice_nano_v2 -- -DSHIELD="settings_reset"
